-- AlterTable
ALTER TABLE `teachers` ADD COLUMN `email` VARCHAR(100) NULL,
    ADD COLUMN `faculty` VARCHAR(100) NULL,
    ADD COLUMN `phone` VARCHAR(20) NULL,
    ADD COLUMN `status` VARCHAR(50) NOT NULL DEFAULT 'Đang dạy',
    ADD COLUMN `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);
