-- AlterTable
ALTER TABLE `students`
  ADD COLUMN `major` VARCHAR(100) NULL,
  ADD COLUMN `advisor_name` VARCHAR(100) NULL,
  ADD COLUMN `email` VARCHAR(100) NULL,
  ADD COLUMN `phone` VARCHAR(20) NULL,
  ADD COLUMN `avatar_url` VARCHAR(255) NULL,
  ADD COLUMN `status` ENUM('active', 'locked') NOT NULL DEFAULT 'active',
  ADD COLUMN `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0);
